/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TratamientosRouteImport } from './routes/tratamientos'
import { Route as FinanzasRouteImport } from './routes/finanzas'
import { Route as EspecialistasRouteImport } from './routes/especialistas'
import { Route as ComisionesRouteImport } from './routes/comisiones'
import { Route as CitasRouteImport } from './routes/citas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIndexRouteImport } from './routes/pacientes.index'
import { Route as PacientesPatientIdRouteImport } from './routes/pacientes.$patientId'

const TratamientosRoute = TratamientosRouteImport.update({
  id: '/tratamientos',
  path: '/tratamientos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanzasRoute = FinanzasRouteImport.update({
  id: '/finanzas',
  path: '/finanzas',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialistasRoute = EspecialistasRouteImport.update({
  id: '/especialistas',
  path: '/especialistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComisionesRoute = ComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const CitasRoute = CitasRouteImport.update({
  id: '/citas',
  path: '/citas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIndexRoute = PacientesIndexRouteImport.update({
  id: '/pacientes/',
  path: '/pacientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesPatientIdRoute = PacientesPatientIdRouteImport.update({
  id: '/pacientes/$patientId',
  path: '/pacientes/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/comisiones': typeof ComisionesRoute
  '/especialistas': typeof EspecialistasRoute
  '/finanzas': typeof FinanzasRoute
  '/tratamientos': typeof TratamientosRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/comisiones': typeof ComisionesRoute
  '/especialistas': typeof EspecialistasRoute
  '/finanzas': typeof FinanzasRoute
  '/tratamientos': typeof TratamientosRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes': typeof PacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citas': typeof CitasRoute
  '/comisiones': typeof ComisionesRoute
  '/especialistas': typeof EspecialistasRoute
  '/finanzas': typeof FinanzasRoute
  '/tratamientos': typeof TratamientosRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/pacientes/': typeof PacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citas'
    | '/comisiones'
    | '/especialistas'
    | '/finanzas'
    | '/tratamientos'
    | '/pacientes/$patientId'
    | '/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citas'
    | '/comisiones'
    | '/especialistas'
    | '/finanzas'
    | '/tratamientos'
    | '/pacientes/$patientId'
    | '/pacientes'
  id:
    | '__root__'
    | '/'
    | '/citas'
    | '/comisiones'
    | '/especialistas'
    | '/finanzas'
    | '/tratamientos'
    | '/pacientes/$patientId'
    | '/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitasRoute: typeof CitasRoute
  ComisionesRoute: typeof ComisionesRoute
  EspecialistasRoute: typeof EspecialistasRoute
  FinanzasRoute: typeof FinanzasRoute
  TratamientosRoute: typeof TratamientosRoute
  PacientesPatientIdRoute: typeof PacientesPatientIdRoute
  PacientesIndexRoute: typeof PacientesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tratamientos': {
      id: '/tratamientos'
      path: '/tratamientos'
      fullPath: '/tratamientos'
      preLoaderRoute: typeof TratamientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finanzas': {
      id: '/finanzas'
      path: '/finanzas'
      fullPath: '/finanzas'
      preLoaderRoute: typeof FinanzasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialistas': {
      id: '/especialistas'
      path: '/especialistas'
      fullPath: '/especialistas'
      preLoaderRoute: typeof EspecialistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comisiones': {
      id: '/comisiones'
      path: '/comisiones'
      fullPath: '/comisiones'
      preLoaderRoute: typeof ComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citas': {
      id: '/citas'
      path: '/citas'
      fullPath: '/citas'
      preLoaderRoute: typeof CitasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/': {
      id: '/pacientes/'
      path: '/pacientes'
      fullPath: '/pacientes/'
      preLoaderRoute: typeof PacientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$patientId': {
      id: '/pacientes/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof PacientesPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitasRoute: CitasRoute,
  ComisionesRoute: ComisionesRoute,
  EspecialistasRoute: EspecialistasRoute,
  FinanzasRoute: FinanzasRoute,
  TratamientosRoute: TratamientosRoute,
  PacientesPatientIdRoute: PacientesPatientIdRoute,
  PacientesIndexRoute: PacientesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
